### ISSUE TITLE
När bollarna tar slut.

### ISSUE THREAD

**Issue by Dragonslayer544** [OscarLinnarsson/Help-Me-Home#32]
När bollarna tar slut måste något hända. Antingen att man vinner eller förlorar och navigeras till en meny.

**Comment by GustavLindahl** [comment]
Asså antingen det, eller att det bara kommer upp en text där det står att man förlora och sen trycker man typ spacebar för att starta om. Eller bara ha en resetbutton hela tiden. Det är min tanke iaf

**Comment by OscarLinnarsson** [comment]
Nja, tänk om den sista bollen gör så att bygget välter in i mål typ? Isf skulle man kunna ha att en "börja om spelet" timer startar när man har slut på bollar typ. 

Alternativt så har man bara en knapp för att start om banan.

**Comment by OscarLinnarsson** [comment]
Haha, oj min hjärna måste ha varit avstängd när jag läste din kommentar Gustav. Jag har lagt till en knapp för att starta om nu iaf så jag ser denna issue som löst nu :)
