### ISSUE TITLE
Max antal bollar

### ISSUE THREAD

**Issue by OscarLinnarsson** [OscarLinnarsson/Help-Me-Home#8]
När man spelar en bana så ska man ha ett begränsat antal bollar att bygga sin struktur med

**Comment by Dragonslayer544** [comment]
fixat, men inte på ett snyggt sätt. Lyckades inte använda mig av konstanter i klassen "Const". Istället är det ett fast värde på 20 i en if-sats i klassen Game.

**Comment by OscarLinnarsson** [comment]
vad var problemet med att använda konstanten?

**Comment by OscarLinnarsson** [comment]
Ah, du måste säga att konstanten är statisk. Det gör du på följande sätt

public static int <variabelnamn> = 20;

**Comment by OscarLinnarsson** [comment]
Done
